/**
 * @file audio_output.h
 * @brief Audio reconstruction, I2S transmission, and PWM output interfaces.
 */

#ifndef AUDIO_OUTPUT_H
#define AUDIO_OUTPUT_H

#ifdef __cplusplus
extern "C" {
#endif

#include "stm32f4xx_hal.h"

#define AUDIO_OUT_BUF_LEN 512U

/** @brief Selects the signal generated by the audio output stage. */
typedef enum
{
  AUDIO_OUTPUT_MODE_SILENCE = 0, /**< Output silence while draining live input. */
  AUDIO_OUTPUT_MODE_TEST_TONE,   /**< Output the internal sine-wave test tone. */
  AUDIO_OUTPUT_MODE_MIC_MONITOR  /**< Output samples from the live-input ring. */
} AudioOutput_Mode_t;

/** @brief I2S/DMA startup state and callback health. */
typedef struct
{
  uint32_t start_status;           /**< HAL status returned by output startup. */
  uint32_t i2s_state_before_start; /**< HAL I2S state before DMA startup. */
  uint32_t i2s_state_after_start;  /**< HAL I2S state after DMA startup. */
  uint32_t i2s_error_code;         /**< Most recent HAL I2S error code. */
  uint32_t dma_state_before_start; /**< HAL TX-DMA state before startup. */
  uint32_t dma_state_after_start;  /**< HAL TX-DMA state after startup. */
  uint32_t dma_error_code;         /**< Most recent HAL TX-DMA error code. */
  uint32_t runtime_error_count;    /**< I2S runtime error callback count. */
  uint32_t half_callback_count;    /**< TX DMA half-complete callbacks. */
  uint32_t full_callback_count;    /**< TX DMA complete callbacks. */
  uint32_t fill_count;             /**< TX buffer halves filled. */
  uint32_t last_callback_tick_ms;  /**< HAL tick of the latest TX callback. */
  uint8_t hdmatx_is_null;          /**< Nonzero when the I2S TX-DMA handle is absent. */
  uint8_t ready;                   /**< Nonzero after output data has been prepared. */
} AudioOutputTransportState;

/** @brief Measurements derived from samples written to the TX DMA buffer. */
typedef struct
{
  uint32_t peak_s16;            /**< Latest transmitted S16 peak. */
  uint32_t abs_avg_s16;         /**< Latest transmitted mean S16 magnitude. */
  uint32_t level_smooth_s16;    /**< Smoothed transmitted S16 level. */
  uint32_t update_count;        /**< Diagnostic blocks measured. */
  uint32_t limiter_sample_count; /**< Samples processed by the output limiter. */
} AudioOutputTxDiagnostics;

/** @brief Runtime output settings adjustable by the application or debugger. */
typedef struct
{
  AudioOutput_Mode_t mode;             /**< Selected audio output mode. */
  uint32_t test_tone_divider;          /**< Test-tone amplitude divisor. */
  uint32_t test_tone_frequency_hz;     /**< Requested test-tone frequency. */
  uint32_t test_tone_frequency_applied_hz; /**< Clamped test-tone frequency. */
  uint32_t test_tone_phase_step_q16;   /**< Test-tone phase increment in Q16. */
  uint32_t monitor_gain_q8;            /**< Legacy S32 monitor gain in Q8. */
  uint32_t repeat_factor;              /**< Output repetitions per ring sample. */
  uint32_t ring_prefill_threshold;     /**< Samples required before playback starts. */
  uint8_t force_test_tone;             /**< Nonzero to override mode with test tone. */
} AudioOutputControls;

/** @brief Producer/consumer state for the live-input ring buffer. */
typedef struct
{
  uint32_t push_sample_count;     /**< Samples accepted from input producers. */
  uint32_t pop_sample_count;      /**< Samples consumed by output. */
  uint32_t underrun_sample_count; /**< Samples missing when output needed data. */
  uint32_t overrun_sample_count;  /**< Input samples dropped because the ring was full. */
  uint32_t available_samples;     /**< Current queued sample count. */
  uint32_t available_min_samples; /**< Minimum observed queued sample count. */
  uint32_t available_max_samples; /**< Maximum observed queued sample count. */
  int16_t last_sample_s16;        /**< Most recently consumed sample. */
  uint8_t streaming;              /**< Nonzero after the prefill threshold is met. */
} AudioOutputRingState;

/** @brief PWM transport state and output-level diagnostics. */
typedef struct
{
  uint32_t start_status;          /**< Overall PWM output startup status. */
  uint32_t pwm_start_status;      /**< HAL PWM-channel startup status. */
  uint32_t timer_start_status;    /**< HAL sample-timer startup status. */
  uint32_t sample_count;          /**< PWM samples emitted. */
  uint32_t samples_per_sec;       /**< Measured PWM sample rate. */
  uint32_t last_duty;             /**< Most recently written PWM duty count. */
  uint32_t peak_s16;              /**< Maximum observed S16 magnitude. */
  uint32_t last_peak_s16;         /**< Magnitude of the latest S16 sample. */
  uint32_t level_smooth_s16;      /**< Smoothed S16 output level. */
  uint32_t clip_count;            /**< Full-scale S16 samples observed. */
  int32_t quantization_error_q16; /**< Noise-shaping quantization error in Q16. */
  int16_t last_sample_s16;        /**< Most recently converted S16 sample. */
  uint8_t noise_shaping_enabled;  /**< Nonzero to enable PWM error feedback. */
  uint8_t ready;                  /**< Nonzero after PWM output starts. */
} AudioPwmOutputState;

/** @brief I2S output transport state. */
extern volatile AudioOutputTransportState audio_out_transport;

/** @brief Transmitted-sample measurements and limiter count. */
extern volatile AudioOutputTxDiagnostics audio_out_tx_diag;

/** @brief Live output controls. */
extern volatile AudioOutputControls audio_out_controls;

/** @brief Live-input ring-buffer state. */
extern volatile AudioOutputRingState audio_out_ring;

/** @brief PWM output transport and signal diagnostics. */
extern volatile AudioPwmOutputState audio_pwm_out_state;

/**
 * @brief Start I2S audio transmission using circular DMA.
 * @param hi2s Configured I2S transmit handle.
 * @return HAL_OK on success; otherwise HAL_ERROR or the HAL startup error.
 */
HAL_StatusTypeDef AudioOutput_Start(I2S_HandleTypeDef *hi2s);

/**
 * @brief Select the signal generated by the audio output stage.
 * @param mode Desired output mode.
 */
void AudioOutput_SetMode(AudioOutput_Mode_t mode);

/**
 * @brief Fill one I2S TX buffer region with stereo output samples.
 * @param buf Destination buffer of I2S half-words.
 * @param len Number of half-words to fill.
 */
void AudioOutput_FillBlock(uint16_t *buf, uint32_t len);

/**
 * @brief Convert and enqueue signed 32-bit monitor samples.
 * @param samples Source samples.
 * @param count Number of source samples.
 */
void AudioOutput_PushSamplesS32(const int32_t *samples, uint32_t count);

/**
 * @brief Enqueue reconstructed signed 16-bit samples.
 * @param samples Source samples.
 * @param count Number of source samples.
 */
void AudioOutput_PushSamplesS16(const int16_t *samples, uint32_t count);

/**
 * @brief Record an error reported by the active output I2S peripheral.
 * @param hi2s I2S handle supplied by the HAL error callback.
 */
void AudioOutput_HandleI2sError(I2S_HandleTypeDef *hi2s);

/**
 * @brief Start the legacy PWM audio-output path.
 * @param pwm_htim Timer providing the PWM carrier.
 * @param pwm_channel HAL channel identifier for the PWM output.
 * @param sample_htim Timer generating audio-rate sample interrupts.
 * @return HAL_OK on success; otherwise the HAL startup error.
 */
HAL_StatusTypeDef AudioPwmOutput_Start(TIM_HandleTypeDef *pwm_htim,
                                       uint32_t pwm_channel,
                                       TIM_HandleTypeDef *sample_htim);

/**
 * @brief Convert and emit one PWM audio sample.
 * @param htim Timer handle associated with the sample tick.
 */
void AudioPwmOutput_HandleSampleTimer(TIM_HandleTypeDef *htim);

/**
 * @brief Handle the PWM sample-timer update interrupt when pending.
 * @param htim Timer handle associated with the interrupt.
 * @return 1 when the update interrupt was handled; otherwise 0.
 */
uint8_t AudioPwmOutput_HandleSampleTimerIrq(TIM_HandleTypeDef *htim);

/** @brief Update the measured PWM output sample rate. */
void AudioPwmOutput_UpdateDiagnostics(void);

#ifdef __cplusplus
}
#endif

#endif /* AUDIO_OUTPUT_H */
